from src.catalog.product.api.schemas.schemas import (
    CategoryNestedSchema,
    SupplierNestedSchema,
    ProductImageReadSchema,
    ProductImageReferenceSchema,
    ProductImageActionSchema,
    ProductAttributeSchema,
    ProductAttributeReadSchema,
    ProductAttributeCreateSchema,
    ProductAttributeUpdateSchema,
    ProductAttributeListResponse,
    ProductCreateSchema,
    ProductUpdateSchema,
    ProductReadSchema,
    ProductListResponse,
    FilterOptionSchema,
    FilterSchema,
    CatalogFiltersRequestSchema,
    CatalogFiltersResponse,
    # ProductRelation
    RelationTypeEnum,
    ProductRelationCreateSchema,
    ProductRelationUpdateSchema,
    ProductRelationReadSchema,
    ProductRecommendationItemSchema,
    PaginationSchema,
    ProductRelationListResponse,
)

__all__ = [
    "CategoryNestedSchema",
    "SupplierNestedSchema",
    "ProductImageReadSchema",
    "ProductImageReferenceSchema",
    "ProductImageActionSchema",
    "ProductAttributeSchema",
    "ProductAttributeReadSchema",
    "ProductAttributeCreateSchema",
    "ProductAttributeUpdateSchema",
    "ProductAttributeListResponse",
    "ProductCreateSchema",
    "ProductUpdateSchema",
    "ProductReadSchema",
    "ProductListResponse",
    "FilterOptionSchema",
    "FilterSchema",
    "CatalogFiltersRequestSchema",
    "CatalogFiltersResponse",
    # ProductRelation
    "RelationTypeEnum",
    "ProductRelationCreateSchema",
    "ProductRelationUpdateSchema",
    "ProductRelationReadSchema",
    "ProductRecommendationItemSchema",
    "PaginationSchema",
    "ProductRelationListResponse",
]
