"""add cms

Revision ID: 30f29f06eee8
Revises: 1483ef328d48
Create Date: 2026-03-07 12:47:16.289614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f29f06eee8'
down_revision: Union[str, Sequence[str], None] = '1483ef328d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cms_seo_page_slug_fkey'), 'cms_seo', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('cms_seo_page_slug_fkey'), 'cms_seo', 'cms_pages', ['page_slug'], ['slug'], ondelete='CASCADE')
    # ### end Alembic commands ###
