"""add phone

Revision ID: 737ae7b1a16d
Revises: 956936928696
Create Date: 2026-03-31 22:46:28.792506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737ae7b1a16d'
down_revision: Union[str, Sequence[str], None] = '956936928696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_relation_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('relation_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_relations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('related_product_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'related_product_id', 'relation_type', name='uq_product_relations_unique')
    )
    op.create_index('ix_product_relations_product_id', 'product_relations', ['product_id'], unique=False)
    op.create_index('ix_product_relations_related_product_id', 'product_relations', ['related_product_id'], unique=False)
    op.create_index('ix_product_relations_relation_type', 'product_relations', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_relations_relation_type', table_name='product_relations')
    op.drop_index('ix_product_relations_related_product_id', table_name='product_relations')
    op.drop_index('ix_product_relations_product_id', table_name='product_relations')
    op.drop_table('product_relations')
    op.drop_table('product_relation_audit_logs')
    # ### end Alembic commands ###
