"""add_product_type_image

Revision ID: 956936928696
Revises: a57126fab9cf
Create Date: 2026-03-20 21:52:07.831860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956936928696'
down_revision: Union[str, Sequence[str], None] = 'a57126fab9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_type_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_type_id', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['product_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_history.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type_id')
    )
    op.create_index('ix_product_type_images_product_type_id', 'product_type_images', ['product_type_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_type_images_product_type_id', table_name='product_type_images')
    op.drop_table('product_type_images')
    # ### end Alembic commands ###
