"""add_groupble

Revision ID: a2c8b26ded9c
Revises: 737ae7b1a16d
Create Date: 2026-04-04 03:49:59.110977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c8b26ded9c'
down_revision: Union[str, Sequence[str], None] = '737ae7b1a16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attributes', sa.Column('is_groupable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_attributes', 'is_groupable')
    # ### end Alembic commands ###
