"""move_device_type_from_products_to_categories

Revision ID: a57126fab9cf
Revises: ba0dcf155658
Create Date: 2026-03-18 01:34:00.834400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57126fab9cf'
down_revision: Union[str, Sequence[str], None] = 'ba0dcf155658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('device_type_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'categories', 'product_types', ['device_type_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_products_product_type_id'), table_name='products')
    op.drop_constraint(op.f('products_product_type_id_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'product_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_product_type_id_fkey'), 'products', 'product_types', ['product_type_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_products_product_type_id'), 'products', ['product_type_id'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'device_type_id')
    # ### end Alembic commands ###
