"""add cms

Revision ID: b30e278ddd8d
Revises: a760c7a56410
Create Date: 2026-03-07 12:16:21.243951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30e278ddd8d'
down_revision: Union[str, Sequence[str], None] = 'a760c7a56410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pav_attribute_id', 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index('ix_pav_product_id', 'product_attribute_values', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pav_product_id', table_name='product_attribute_values')
    op.drop_index('ix_pav_attribute_id', table_name='product_attribute_values')
    # ### end Alembic commands ###
