"""add cms

Revision ID: ba0dcf155658
Revises: 30f29f06eee8
Create Date: 2026-03-13 20:39:20.557617

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ba0dcf155658'
down_revision: Union[str, Sequence[str], None] = '30f29f06eee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.BigInteger(), nullable=False),
    sa.Column('upload_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_history.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id')
    )
    op.create_index('ix_manufacturer_images_manufacturer_id', 'manufacturer_images', ['manufacturer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manufacturer_images_manufacturer_id', table_name='manufacturer_images')
    op.drop_table('manufacturer_images')
    # ### end Alembic commands ###
